[tool.poetry]
name = "omni-py"
version = "0.1.0"
description = ""
authors = ["almutlue <almut.lue@gmail.com>"]
readme = "README.md"
packages = [{include = "omni-py"}]
homepage = "https://github.com/almutlue/omni-py"
repository = "https://github.com/almutlue/omni-py"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python"
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
black = "^23.12.0"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
