[tool.poetry]
name = "omni"
version = "0.1.0"
description = ""
authors = ["almutlue <almut.lue@gmail.com>"]
readme = "README.md"
packages = [{include = "omni"}]
homepage = "https://github.com/almutlue/omni-py"
repository = "https://github.com/almutlue/omni-py"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python"
]

[tool.poetry.dependencies]
python = "^3.10"
omni-schema = {git = "https://github.com/omnibenchmark/omni-schema.git", rev = "e3daebe9f75a6225adb674da5efaa477981baa1e"}
typer = {extras = ["all"], version = "^0.12.3"}
typing-extensions = "^4.11.0"
easybuild="^4.9.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
black = "^23.12.0"
pytest-cov = "^4.1.0"

[tool.poetry.scripts]
ob = 'omni.cli.main:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
